"""Config-driven MoM localization + rendering.

SINGLE SOURCE OF TRUTH for the Minutes-of-Meeting layout across every language. The LLM produces
ONLY structured content (see `CONTENT_SCHEMA` / `parse_content`); this module owns section order,
headings, field labels, separators, footer, speaker-label localization, and metadata placement.

Adding a new language = add ONE entry to MOM_LABELS. No business logic changes.

Forward-compatibility: the content is a set of structured objects (`header`, `attendees`,
`speaker_notes`, `action_items`). New sub-fields can be added to any object and the renderer keeps
working — `parse_content` ignores unknown keys and supplies defaults for missing ones.

Localization rules enforced here:
  * Fixed document strings (headings/labels/footer) come from MOM_LABELS — never the LLM.
  * Identifiers/proper nouns are never touched (they only live inside content values).
  * Generic speaker placeholders ([Speaker_1], Speaker A, ...) → localized "Speaker N".
  * Date/Time: LLM value used only if explicitly extracted (D2), else the deterministic backend
    metadata (ISO-8601 + 24h). The renderer never asks the LLM to format a date.
"""

import json
import logging
import os
import re

logger = logging.getLogger(__name__)

# Brand / product name — an identifier, NEVER translated.
BRAND = "AngelBot.AI"


def _load_glossary():
    """Load the terminology glossary (termbase). Config-driven: edit glossary.json, no code change.
    Returns (dnt_list, terms_dict). Degrades to empty on any error so translation still works."""
    path = os.path.join(os.path.dirname(__file__), "glossary.json")
    try:
        with open(path, encoding="utf-8") as f:
            g = json.load(f)
        dnt = [t for t in g.get("dnt", []) if isinstance(t, str) and t.strip()]
        terms = {k: v for k, v in g.get("terms", {}).items()
                 if isinstance(k, str) and isinstance(v, dict)}
        return dnt, terms
    except Exception as e:  # noqa: BLE001
        logger.warning(f"[i18n] glossary.json not loaded ({e}); using empty glossary")
        return [], {}


# DNT = do-not-translate (kept verbatim). TERMS = approved per-language translations {src: {lang: tr}}.
GLOSSARY_DNT, GLOSSARY_TERMS = _load_glossary()

# The renderer owns section order (not the LLM).
SECTION_ORDER = ["agenda", "attendees", "summary", "key_figures", "speaker_notes", "decisions", "action_items", "purpose"]

_RULE = "=" * 80   # major separator (header/footer)
_SUB = "_" * 80    # minor separator (between sections)

# Documentation of the content contract the LLM must emit (kept in sync with parse_content).
CONTENT_SCHEMA = {
    "header": {"topic": "str", "meeting_date": "str?", "meeting_time": "str?", "venue": "str?"},
    "agenda": ["str"],
    "attendees": [{"name": "str", "role": "str"}],
    "summary": "str",
    "key_points": ["str"],    # the meeting's substantive points, one per topic discussed
    "key_figures": ["str"],   # OPTIONAL — omitted entirely when the meeting has no figures
    "speaker_notes": [{"speaker": "str", "points": ["str"]}],
    "decisions": ["str"],
    "action_items": [{"task": "str", "assigned_to": "str", "assigned_by": "str", "due": "str"}],
    "purpose": "str",
}

# ─────────────────────────────────────────────────────────────────────────────
# Localization table. Every fixed string the document can show, per language.
# `generated_by` uses {brand} so the brand stays an untranslated identifier.
# NOTE: non-English strings are a consistent first pass — flag for native-speaker review; they are
# uniform from day one, which is the enterprise requirement.
# ─────────────────────────────────────────────────────────────────────────────
MOM_LABELS = {
    "English": {
        "title": "Minutes of Meeting",
        "date": "Date", "time": "Time", "venue": "Venue",
        "agenda": "AGENDA", "attendees": "ATTENDEES", "summary": "SUMMARY",
        "key_points": "KEY DISCUSSION POINTS",
        "key_figures": "KEY FIGURES", "speaker_notes": "SPEAKER-WISE NOTES", "decisions": "DECISIONS TAKEN",
        "action_items": "ACTION ITEMS", "purpose": "PURPOSE OF MEETING",
        "assigned_to": "Assigned to", "assigned_by": "Assigned by", "due_on": "Due on",
        "speaker": "Speaker", "not_specified": "Not specified", "none_stated": "None explicitly stated.",
        "regards": "Regards,", "generated_by": "Generated by {brand}",
    },
    "Hindi": {
        "title": "बैठक का कार्यवृत्त",
        "date": "दिनांक", "time": "समय", "venue": "स्थान",
        "agenda": "कार्यसूची", "attendees": "उपस्थित लोग", "summary": "सारांश",
        "key_points": "मुख्य चर्चा बिंदु", "key_figures": "मुख्य आंकड़े",
        "speaker_notes": "वक्ता-वार टिप्पणियाँ", "decisions": "लिए गए निर्णय",
        "action_items": "कार्य बिंदु", "purpose": "बैठक का उद्देश्य",
        "assigned_to": "को सौंपा गया", "assigned_by": "द्वारा सौंपा गया", "due_on": "नियत तिथि",
        "speaker": "वक्ता", "not_specified": "निर्दिष्ट नहीं", "none_stated": "स्पष्ट रूप से उल्लेख नहीं किया गया।",
        "regards": "सादर,", "generated_by": "{brand} द्वारा जनित",
    },
    "Chinese (Simplified)": {
        "title": "会议纪要",
        "date": "日期", "time": "时间", "venue": "地点",
        "agenda": "议程", "attendees": "与会人员", "summary": "摘要",
        "key_points": "重点讨论事项", "key_figures": "关键数据",
        "speaker_notes": "发言人纪要", "decisions": "已做决定",
        "action_items": "行动项", "purpose": "会议目的",
        "assigned_to": "指定给", "assigned_by": "指定由", "due_on": "截止日期",
        "speaker": "发言人", "not_specified": "未指定", "none_stated": "未明确说明。",
        "regards": "致意，", "generated_by": "由 {brand} 生成",
    },
    "Russian": {
        "title": "Протокол совещания",
        "date": "Дата", "time": "Время", "venue": "Место",
        "agenda": "ПОВЕСТКА ДНЯ", "attendees": "УЧАСТНИКИ", "summary": "КРАТКОЕ СОДЕРЖАНИЕ",
        "key_points": "КЛЮЧЕВЫЕ ВОПРОСЫ", "key_figures": "КЛЮЧЕВЫЕ ПОКАЗАТЕЛИ",
        "speaker_notes": "ЗАМЕТКИ ПО ВЫСТУПАЮЩИМ", "decisions": "ПРИНЯТЫЕ РЕШЕНИЯ",
        "action_items": "ПОРУЧЕНИЯ", "purpose": "ЦЕЛЬ СОВЕЩАНИЯ",
        "assigned_to": "Ответственный", "assigned_by": "Поручил", "due_on": "Срок",
        "speaker": "Выступающий", "not_specified": "Не указано", "none_stated": "Явно не указано.",
        "regards": "С уважением,", "generated_by": "Сгенерировано {brand}",
    },
    "Hebrew": {
        "title": "פרוטוקול ישיבה",
        "date": "תאריך", "time": "שעה", "venue": "מקום",
        "agenda": "סדר יום", "attendees": "משתתפים", "summary": "סיכום",
        "key_points": "נקודות דיון מרכזיות", "key_figures": "נתונים מרכזיים",
        "speaker_notes": "הערות לפי דובר", "decisions": "החלטות שהתקבלו",
        "action_items": "פריטי פעולה", "purpose": "מטרת הישיבה",
        "assigned_to": "הוקצה ל", "assigned_by": "הוקצה על ידי", "due_on": "תאריך יעד",
        "speaker": "דובר", "not_specified": "לא צוין", "none_stated": "לא צוין במפורש.",
        "regards": "בברכה,", "generated_by": "נוצר על ידי {brand}",
    },
    "Arabic": {
        "title": "محضر الاجتماع",
        "date": "التاريخ", "time": "الوقت", "venue": "المكان",
        "agenda": "جدول الأعمال", "attendees": "الحضور", "summary": "ملخص",
        "key_points": "نقاط النقاش الرئيسية", "key_figures": "الأرقام الرئيسية",
        "speaker_notes": "ملاحظات حسب المتحدث", "decisions": "القرارات المتخذة",
        "action_items": "بنود العمل", "purpose": "الغرض من الاجتماع",
        "assigned_to": "مُسند إلى", "assigned_by": "مُسند من", "due_on": "تاريخ الاستحقاق",
        "speaker": "المتحدث", "not_specified": "غير محدد", "none_stated": "غير مذكور صراحةً.",
        "regards": "مع التحية،", "generated_by": "تم الإنشاء بواسطة {brand}",
    },
}

SUPPORTED_LANGS = list(MOM_LABELS.keys())


def _merged(name):
    """A language's labels layered over English.

    Non-English sets are allowed to be incomplete, and were: none of the five carried a
    `key_figures` label, so rendering a MoM with figures in Hindi raised KeyError inside the
    renderer. Layering over English means a missing label degrades to the English word — the
    section still renders — instead of taking the whole document down.
    """
    if name == "English":
        return MOM_LABELS["English"]
    return {**MOM_LABELS["English"], **MOM_LABELS[name]}


def labels_for(lang):
    """Resolve a language name (tolerant of aliases like 'chinese', 'zh') to its label set.
    Falls back to English so an unconfigured language degrades gracefully rather than breaking."""
    if not lang:
        return MOM_LABELS["English"]
    if lang in MOM_LABELS:
        return _merged(lang)
    low = lang.strip().lower()
    for name in MOM_LABELS:
        if name.lower() == low:
            return _merged(name)
    alias = {"chinese": "Chinese (Simplified)", "zh": "Chinese (Simplified)", "mandarin": "Chinese (Simplified)",
             "hindi": "Hindi", "hi": "Hindi", "russian": "Russian", "ru": "Russian",
             "hebrew": "Hebrew", "he": "Hebrew", "arabic": "Arabic", "ar": "Arabic",
             "english": "English", "en": "English"}
    for key, name in alias.items():
        if key in low:
            return _merged(name)
    return MOM_LABELS["English"]


# Generic speaker placeholder: [Speaker_1], Speaker A, speaker 3, [speaker_02] ...  A real name won't match.
_SPEAKER_RE = re.compile(r'^\[?\s*speaker[\s_]*([0-9]+|[A-Za-z])\s*\]?$', re.IGNORECASE)


def localize_speaker(value, L):
    """Generic speaker placeholder → localized 'Speaker N'. A real name passes through unchanged."""
    if not value:
        return value
    v = str(value).strip()
    m = _SPEAKER_RE.match(v)
    if not m:
        return v                      # real name / anything non-generic → keep verbatim
    tok = m.group(1)
    n = tok if tok.isdigit() else str(ord(tok.upper()) - 64)   # A->1, B->2, ...
    return f"{L['speaker']} {n}"


# ─────────────────────────────────────────────────────────────────────────────
# Parsing, validation, deterministic repair
# ─────────────────────────────────────────────────────────────────────────────
_CORE_KEYS = {"header", "topic", "agenda", "attendees", "summary",
              "speaker_notes", "decisions", "action_items", "purpose"}


def _extract_json(raw):
    """Pull a JSON object out of a model response, tolerating ```json fences and surrounding prose."""
    if isinstance(raw, dict):
        return raw
    s = (raw or "").strip()
    if "```" in s:
        parts = s.split("```")
        if len(parts) >= 2:
            s = parts[1]
            if s.lstrip().lower().startswith("json"):
                s = s.lstrip()[4:]
    a, b = s.find("{"), s.rfind("}")
    if a != -1 and b != -1 and b > a:
        s = s[a:b + 1]
    try:
        return json.loads(s)
    except Exception:
        return {}


def _repair_json(raw):
    """Deterministic (no-LLM) repair of common malformed-JSON issues: markdown fences, leading prose,
    trailing commas, and unclosed braces/brackets (truncated output). Returns a parsed dict or {}."""
    s = str(raw or "").strip()
    if "```" in s:
        parts = s.split("```")
        if len(parts) >= 2:
            s = parts[1]
            if s.lstrip().lower().startswith("json"):
                s = s.lstrip()[4:]
    a = s.find("{")
    if a == -1:
        return {}
    s = s[a:]
    s = re.sub(r',\s*([}\]])', r'\1', s)                 # trailing commas
    s = s + ("]" * max(0, s.count("[") - s.count("]")))  # close arrays
    s = s + ("}" * max(0, s.count("{") - s.count("}")))  # close objects
    try:
        return json.loads(s)
    except Exception:
        return {}


def is_valid_raw(data):
    """A response is valid if it is a JSON object carrying at least one recognized content key."""
    return isinstance(data, dict) and bool(_CORE_KEYS & set(data.keys()))


def parse_and_validate(raw):
    """Parse an LLM JSON response, with ONE deterministic repair retry before giving up.
    Returns (content_dict, ok). The renderer should only be called when ok is True."""
    data = _extract_json(raw)
    if not is_valid_raw(data):
        data = _repair_json(raw)          # single deterministic repair retry
    ok = is_valid_raw(data)
    return parse_content(data if ok else {}), ok


def _s(x):
    return str(x).strip() if x is not None else ""


def _list(x):
    return x if isinstance(x, list) else []


def _bullets(x):
    """List of strings, tolerant of [{"text": ...}] / [{"point": ...}] for forward-compat."""
    out = []
    for i in _list(x):
        if isinstance(i, dict):
            out.append(_s(i.get("text") or i.get("point") or i.get("item")))
        else:
            out.append(_s(i))
    return [i for i in out if i]


def parse_content(raw):
    """Normalize LLM content (dict OR JSON string) into the canonical schema with safe defaults.
    Missing/malformed fields degrade to empty — never raises. Unknown keys are ignored (forward-compat)."""
    data = raw if isinstance(raw, dict) else _extract_json(raw)
    data = data if isinstance(data, dict) else {}
    header = data.get("header") if isinstance(data.get("header"), dict) else {}
    return {
        "header": {
            "topic": _s(header.get("topic") or data.get("topic")),
            "meeting_date": _s(header.get("meeting_date") or data.get("meeting_date")),
            "meeting_time": _s(header.get("meeting_time") or data.get("meeting_time")),
            "venue": _s(header.get("venue") or data.get("venue")),
        },
        "agenda": _bullets(data.get("agenda")),
        "attendees": [{"name": _s(a.get("name")), "role": _s(a.get("role"))}
                      for a in _list(data.get("attendees")) if isinstance(a, dict)],
        "summary": _s(data.get("summary")),
        "key_points": _bullets(data.get("key_points")),
        "key_figures": _bullets(data.get("key_figures")),
        "speaker_notes": [{"speaker": _s(sn.get("speaker")), "points": _bullets(sn.get("points"))}
                          for sn in _list(data.get("speaker_notes")) if isinstance(sn, dict)],
        "decisions": _bullets(data.get("decisions")),
        "action_items": [{"task": _s(ai.get("task")), "assigned_to": _s(ai.get("assigned_to")),
                          "assigned_by": _s(ai.get("assigned_by")), "due": _s(ai.get("due"))}
                         for ai in _list(data.get("action_items")) if isinstance(ai, dict)],
        "purpose": _s(data.get("purpose")),
    }


# ─────────────────────────────────────────────────────────────────────────────
# Renderer — single source of truth for layout
# ─────────────────────────────────────────────────────────────────────────────
def render_mom(content, lang="English", metadata=None):
    """Render structured `content` into the final MoM text for `lang`. Deterministic: same content +
    metadata always produces byte-identical layout, and every language shares the exact structure.

    metadata: deterministic backend fallback {date, time, venue} (ISO-8601 + 24h). Used only when the
    LLM did not extract that value into content.header (D2)."""
    L = labels_for(lang)
    c = parse_content(content)
    meta = metadata or {}
    ns = L["not_specified"]
    none_stated = L["none_stated"]
    h = c["header"]

    # D2: LLM-extracted header value wins; deterministic backend metadata is the fallback.
    topic = h["topic"]
    date_val = h["meeting_date"] or _s(meta.get("date")) or none_stated
    time_val = h["meeting_time"] or _s(meta.get("time")) or none_stated
    venue_val = h["venue"] or _s(meta.get("venue")) or none_stated

    header = [
        _RULE, "",
        f"{L['title']} | {topic}".rstrip(" |"),
        f"{L['date']}: {date_val}",
        f"{L['time']}: {time_val}",
        f"{L['venue']}: {venue_val}",
        _RULE,
    ]

    def section(heading, body):
        return [heading, *body]

    blocks = [header]

    # AGENDA
    blocks.append(section(L["agenda"], [f"  • {i}" for i in c["agenda"]] or [f"  • {none_stated}"]))

    # ATTENDEES
    att = []
    for a in c["attendees"]:
        name = localize_speaker(a["name"], L)
        att.append(f"  • {name} — {a['role']}" if a["role"] else f"  • {name}")
    blocks.append(section(L["attendees"], att or [f"  • {none_stated}"]))

    # SUMMARY (paragraph)
    blocks.append(section(L["summary"], [f"  {c['summary']}" if c["summary"] else f"  {none_stated}"]))

    # KEY DISCUSSION POINTS — the substantive content of the meeting, one entry per topic.
    # Rendered right after the narrative summary because it is the summary's checklist: the
    # summary is prose and compresses under length pressure, this list does not.
    if c.get("key_points"):
        blocks.append(section(L["key_points"], [f"  • {k}" for k in c["key_points"]]))

    # KEY FIGURES — deliberately OMITTED ENTIRELY when empty, unlike every other section, which
    # falls back to "None explicitly stated." Most meetings (standups, planning, reviews) contain
    # no itemised figures, and an empty "KEY FIGURES: None" heading on those would be noise.
    # Rendering it only when populated makes the section self-conditional: it appears exactly when
    # it has something to say. The section exists because abstractive summarisation reliably drops
    # enumerated figures — the model compresses "eight budget line items" into "a breakdown was
    # presented" to satisfy the summary's length constraint. Giving figures their own home stops
    # them competing with narrative for space.
    if c.get("key_figures"):
        blocks.append(section(L["key_figures"], [f"  • {f}" for f in c["key_figures"]]))

    # SPEAKER-WISE NOTES (skip speakers with no attributed points)
    sn_lines = []
    for sn in c["speaker_notes"]:
        if not sn["points"]:
            continue
        sn_lines.append(f"  {localize_speaker(sn['speaker'], L)}:")
        sn_lines.extend(f"    • {p}" for p in sn["points"])
    blocks.append(section(L["speaker_notes"], sn_lines or [f"  {none_stated}"]))

    # DECISIONS TAKEN
    blocks.append(section(L["decisions"], [f"  • {d}" for d in c["decisions"]] or [f"  • {none_stated}"]))

    # ACTION ITEMS (omit an empty assignee line; due always shows, not_specified if blank)
    ai_lines = []
    for ai in c["action_items"]:
        ai_lines.append(f"  • {ai['task']}")
        if ai["assigned_to"]:
            ai_lines.append(f"    {L['assigned_to']}: {localize_speaker(ai['assigned_to'], L)}")
        if ai["assigned_by"]:
            ai_lines.append(f"    {L['assigned_by']}: {localize_speaker(ai['assigned_by'], L)}")
        ai_lines.append(f"    {L['due_on']}: {ai['due'] or ns}")
    blocks.append(section(L["action_items"], ai_lines or [f"  • {none_stated}"]))

    # PURPOSE OF MEETING (paragraph)
    blocks.append(section(L["purpose"], [f"  {c['purpose']}" if c["purpose"] else f"  {none_stated}"]))

    # Assemble: header ══, AGENDA directly, remaining sections each preceded by ──, then footer.
    parts = ["\n".join(header), "\n".join(blocks[1])]
    for blk in blocks[2:]:
        parts.append(_SUB)
        parts.append("\n".join(blk))
    parts.append(_RULE)
    parts.append(f"{L['regards']}\n{L['generated_by'].format(brand=BRAND)}")

    return "\n\n".join(parts) + "\n"
